# Define your own admin routes here
order_logs:
  prefix: '/_partial/order'
  resource: 'routing/partial/order.yml'

payment_logs:
  prefix: '/_partial/payment'
  resource: 'routing/partial/payment.yml'

shipment_logs:
  prefix: '/_partial/shipment'
  resource: 'routing/partial/shipment.yml'
