<?php
/**
 * This code is generated by the config converter under https://github.com/mamazu/grid-config-converter
 * Feel free to modify the code as you see fit.
 */
use Sylius\Bundle\GridBundle\Grid\AbstractGrid;
use Sylius\Bundle\GridBundle\Builder\Filter\Filter;
use Sylius\Bundle\GridBundle\Builder\Field\Field;
use Sylius\Bundle\GridBundle\Builder\GridBuilderInterface;
use Sylius\Bundle\GridBundle\Builder\ActionGroup\MainActionGroup;
use Sylius\Bundle\GridBundle\Builder\ActionGroup\ItemActionGroup;
use Sylius\Bundle\GridBundle\Builder\ActionGroup\SubItemActionGroup;
use Sylius\Bundle\GridBundle\Builder\ActionGroup\BulkActionGroup;
use Sylius\Bundle\GridBundle\Config\GridConfig;
use Sylius\Bundle\GridBundle\Builder\GridBuilder;
use Sylius\Bundle\GridBundle\Builder\Action\Action;
use Sylius\Bundle\GridBundle\Builder\Action\ShowAction;
use Sylius\Bundle\GridBundle\Builder\Action\CreateAction;
use Sylius\Bundle\GridBundle\Builder\Action\UpdateAction;
use Sylius\Bundle\GridBundle\Builder\Action\DeleteAction;
use Sylius\Bundle\GridBundle\Builder\Field\DateTimeField;
use Sylius\Bundle\GridBundle\Builder\Field\StringField;
use Sylius\Bundle\GridBundle\Builder\Field\TwigField;
class Brille24AdminShipmentLogEntry extends AbstractGrid
{
    public static function getName() : string
    {
        return 'brille24_admin_shipment_log_entry';
    }
    public function buildGrid(GridBuilderInterface $gridBuilder) : void
    {
        $gridBuilder
            ->setDriver('doctrine/orm')
            ->setRepositoryMethod('createByObjectIdQueryBuilder', [
                'objectId' => '$id',
            ])
            ->setDriverOption('class', '%brille24.model.shipment_log_entry.class%')
            ->setLimits([
                100,
            ])
            ->addField(
                TwigField::create('action', '@SyliusUi/Grid/Field/logAction.html.twig')
                ->setLabel('sylius.ui.action')
                ->setOptions([
                    'template' => '@SyliusUi/Grid/Field/logAction.html.twig',
                ])
            )
            ->addField(
                DateTimeField::create('date')
                ->setLabel('sylius.ui.logged_at')
                ->setOptions([
                    'format' => 'd-m-Y H:i:s',
                ])
            )
            ->addField(
                TwigField::create('user', '@Brille24SyliusOrderLogPlugin/Grid/Field/user.html.twig')
                ->setLabel('sylius.ui.user')
                ->setOptions([
                    'template' => '@Brille24SyliusOrderLogPlugin/Grid/Field/user.html.twig',
                ])
            )
            ->addField(
                TwigField::create('data', '@SyliusUi/Grid/Field/logData.html.twig')
                ->setLabel('sylius.ui.changes')
                ->setOptions([
                    'template' => '@SyliusUi/Grid/Field/logData.html.twig',
                ])
            )
        ;
    }
    public static function getResourceClass() : string
    {
        return '%brille24.model.shipment_log_entry.class%';
    }
}
