<?php
/**
 * This code is generated by the config converter under https://github.com/mamazu/grid-config-converter
 * Feel free to modify the code as you see fit.
 */
namespace Brille24\SyliusOrderLogPlugin\Grids;

use Sylius\Bundle\GridBundle\Grid\AbstractGrid;
use Sylius\Bundle\GridBundle\Builder\GridBuilderInterface;
use Sylius\Bundle\GridBundle\Builder\Field\DateTimeField;
use Sylius\Bundle\GridBundle\Builder\Field\TwigField;

class PaymentLogEntryGrid extends AbstractGrid
{
    public function __construct(
        private string $resourceClass
        ) {}

    public static function getName() : string
    {
        return 'brille24_admin_payment_log_entry';
    }
    public function buildGrid(GridBuilderInterface $gridBuilder) : void
    {
        $gridBuilder
            ->setDriver('doctrine/orm')
            ->setRepositoryMethod('createByObjectIdQueryBuilder', [
                'objectId' => '$id',
            ])
            ->setDriverOption('class', $this->resourceClass)
            ->setLimits([
                100,
            ])
            ->addField(
                TwigField::create('action', '@SyliusUi/Grid/Field/logAction.html.twig')
                ->setLabel('sylius.ui.action')
                ->setOptions([
                    'template' => '@SyliusUi/Grid/Field/logAction.html.twig',
                ])
            )
            ->addField(
                DateTimeField::create('date')
                ->setLabel('sylius.ui.logged_at')
                ->setOptions([
                    'format' => 'd-m-Y H:i:s',
                ])
            )
            ->addField(
                TwigField::create('user', '@Brille24SyliusOrderLogPlugin/Grid/Field/user.html.twig')
                ->setLabel('sylius.ui.user')
                ->setOptions([
                    'template' => '@Brille24SyliusOrderLogPlugin/Grid/Field/user.html.twig',
                ])
            )
            ->addField(
                TwigField::create('data', '@SyliusUi/Grid/Field/logData.html.twig')
                ->setLabel('sylius.ui.changes')
                ->setOptions([
                    'template' => '@SyliusUi/Grid/Field/logData.html.twig',
                ])
            )
        ;
    }

    public function getResourceClass() : string
    {
        return $this->resourceClass;
    }
}
